## YAML Template.
---
## Fichero de configuración para UjaVid

spring.datasource.url: jdbc:h2:mem:ujavid;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username: ujavid
spring.datasource.password: secret

spring.jpa.properties.javax.persistence.schema-generation.database.action: none

spring.data.jpa.repositories.bootstrap-mode: default
