## YAML Template.
---
## Fichero de configuración para UjaVid

spring.datasource.url: jdbc:mysql://localhost:33060/ujavid
spring.datasource.username: ujavid
spring.datasource.password: secret

spring.jpa.properties.javax.persistence.schema-generation.database.action: none

spring.data.jpa.repositories.bootstrap-mode: default
